package:
    name: clojupyter
    version: 0.4.1

about:
    description: Clojupyter - Clojure kernel for Jupyter
    home: https://github.com/clojupyter/clojupyter
    licence: MIT

source:
    path: ../target

build:
    number: 1

requirements:
    run:
        - openjdk=8
        - jupyter
        - jupyterlab
